[package]
name = "SnowKernel"
version = "0.1.0"
authors = ["xuserwhat <quicknshell@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
x86 = "0.8.1"
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
uefi = { git = "https://github.com/SnowFlakeOS/uefi.git" }
