[package]
name = "SnowKernel"
version = "0.1.0"
authors = ["xuserwhat <quicknshell@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
x86_64 = "0.1.2"
bitflags = "1.0.1"
uefi = {git = "https://github.com/SnowFlakeOS/uefi"}